### ISSUE TITLE
Any chance of an OSX port?

### ISSUE THREAD

**Issue by 62574353** [Warlockbugs/impulse-booster#1]

**Comment by Warlockbugs** [comment]
What do you mean? All addons are platform-independent. Unless native OSX client disables some vital functionality, then this functionality will simply not work. You can use repacked WINE version for OSX, this is required to work around different filesystem behavior on unix-like systems.

**Comment by 62574353** [comment]
I see! Yes, this is my mistake. Sorry for the misunderstanding--this is a really great addition. Thank you!
