### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by 62574353** [Warlockbugs/impulse-booster#2]
I'm having a conflict with another addon: modui.

I've removed impulsebooster but the addon still shows up in my list. WTF & WDB folders both deleted.

**Comment by Warlockbugs** [comment]
Its possible that you have WINE version installed for some reason. Check for presence Data/patch-b.mpq and remove it.

**Comment by 62574353** [comment]
That was it! Many thanks.

Really wish I could use this, but something about ModUI (https://github.com/obble/modui) doesn't agree with the addon. I'm not sure what the conflict is, but if you have any wisdom or insight I would greatly appreciate it.

**Comment by Warlockbugs** [comment]
Its not a conflict and it has nothing to do with my addon. modui alone spews a lot of errors.

**Comment by 62574353** [comment]
Wasn't trying to imply that it did. Merely a gentle inquiry should you have any advice. Thanks, and have a great day!
