### ISSUE TITLE
Question regarding IBSync on vanilla client

### ISSUE THREAD

**Issue by dabadoo** [Warlockbugs/impulse-booster#3]
How do I enable this feature?

I have been trying to look through the ImpulseBooster.lua between line 212 and 254. This look like the relevant area to me, but i'm not sure where exactly between those lines I need to enable the feature?

This is on the Vanilla 1.12.1 client.

**Comment by Warlockbugs** [comment]
You simply can't, frame limiter cvar was introduced in TBC.
