### ISSUE TITLE
No more need for the Linux Version

### ISSUE THREAD

**Issue by Zebouski** [Warlockbugs/impulse-booster#6]
Ya had linux users downloading an mpq because of how wine loaded filenames. https://bugs.winehq.org/show_bug.cgi?id=34122 this bug has since been closed fixed, so should we be good now to just use the addon version like windows users? I can help test if needed.

**Comment by Warlockbugs** [comment]
At the time some special workarounds were needed to ensure specific loading order in wine, now its been years since its no longer needed. Downloads updated

**Comment by Thaodan** [comment]
Readme hasn't been updated on this in case anyone stumbles on this after updating the readme.
